### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by johnd0e** [juzeon/SydneyQt-browser-extension#1]
1. Chrome: `Cookie status: Error`

2. Edge: `Cookie status: Logged In (User)`
   But when I press "Update Cookies to SydneyQt" I get alarmbox `TypeError: failed to fetch`
   Console:
   >popup.html:1  Access to fetch at 'http://127.0.0.1:61989/cookies' from origin 'chrome-extension://mdcmegnoekeajemakjckfepmcdpdaimk' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
   > chunk-33be06dc.js:5 

SydneyQt.exe is running

**Comment by juzeon** [comment]
Please wait for the next version to release before testing if this could be solved.

**Comment by johnd0e** [comment]
The issue seems fixed with latest SydneyQt release.
